### ISSUE TITLE
Release compatible with current version of standard library

### ISSUE THREAD

**Issue by turion** [gallais/agdarsec#21]
I'm currently trying to include `agdarsec` in `nixpkgs`: https://github.com/NixOS/nixpkgs/pull/100351 But unfortunately it doesn't seem to build (possibly this has to do with the current version of the standard library). I tried `master` (b26230ab714cddc23f1fe242d8a80abbf3b43d4f) and the release v3.0.0.

With `master`, I get these errors:

```
[...]
    /nix/store/1b7jp08xlcbvankbf8aml162zmid00la-standard-library-1.4/src/Expr.agda
    /nix/store/1b7jp08xlcbvankbf8aml162zmid00la-standard-library-1.4/src/Expr.lagda
    /build/source/src/Expr.agda
    /build/source/src/Expr.lagda
    /build/source/Expr.agda
    /build/source/Expr.lagda
    /nix/store/vkm07q5a493h356zmlqzvn7sxc4r0wwv-Agda-2.6.1.2-data/share/ghc-8.10.2/x86_64-linux-ghc-8.10.2/Agda-2.6.1.2/lib/prim/Expr.agda
    /nix/store/vkm07q5a493h356zmlqzvn7sxc4r0wwv-Agda-2.6.1.2-data/share/ghc-8.10.2/x86_64-linux-ghc-8.10.2/Agda-2.6.1.2/lib/prim/Expr.lagda
  when scope checking the declaration
    import Expr
```
It seems like `Expr` cannot be imported. I'm not sure whether it's supposed to be part of `agdarsec` or part of the standard library.

**Comment by gallais** [comment]
`Expr` is part of the examples. It is not part of the library itself.
Cf. the [agda-lib](https://github.com/gallais/agdarsec/blob/master/agdarsec.agda-lib) file indicating that the library's content is in `src/`.

If you want to build `index.agda` and `examples/` then you need a command
akin to what is used on travis:

https://github.com/gallais/agdarsec/blob/b26230ab714cddc23f1fe242d8a80abbf3b43d4f/.travis.yml#L29

**Comment by turion** [comment]
Makes sense :) I've updated the nixpkgs PR. It should be soon part of nixpkgs, which means you get semi-automatic updates if it is out of sync with the standard library.
