### ISSUE TITLE
Relationship between Data.List.Sized and Agda's sized types?

### ISSUE THREAD

**Issue by langston-barrett** [gallais/agdarsec#7]
Hi, this is more of a question than anything, but I'm wondering if there's any relationship between the module `Data.List.Sized` and Agda's [sized types](https://agda.readthedocs.io/en/v2.5.3/language/sized-types.html). The latter have come in handy for me to be able to prove termination of some functions, and my impression is that the former are used to make sure the parsers are total, is this right? Thanks in advance for clarifying.

**Comment by gallais** [comment]
The `Nat` indices' sole purpose is indeed to guarantee the termination of the parsers.

`Data.List.Sized` is more of an analogue of `Data.Vec` but with the index pushed in.
The [proof of equality](https://github.com/gallais/agdarsec/blob/master/src/Data/List/Sized.agda#L24) is marked with a point to tell Agda its particular value can be
ignored (the only thing that matters is that there is such a proof) and even erased
at compile time.

You could use sized types instead if the combinators defined in `Induction.Nat.Strong`
were defined in terms of `Size`s like Saizan has done [on his fork](https://github.com/Saizan/agdarsec/commit/0aa19d78cc7b869692b82ea513d5d23c358e1f51). You may run into
trouble when trying to define the parser combinators though cf. agda/agda#2903

**Comment by langston-barrett** [comment]
Thanks for the clarification! That's exactly what I was wondering.
